// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxuH_7xfnrzLMam4R41Uds7ThxUfDxP4',
    appId: '1:1066116333121:web:47f2466821b5eadbb650c0',
    messagingSenderId: '1066116333121',
    projectId: 'skipper-21480',
    authDomain: 'skipper-21480.firebaseapp.com',
    storageBucket: 'skipper-21480.appspot.com',
    measurementId: 'G-F8MC00K4JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUH3OB83MRZVRf0ev4fm6_0dVdAJXCcSc',
    appId: '1:1066116333121:android:9454867e83dbfa34b650c0',
    messagingSenderId: '1066116333121',
    projectId: 'skipper-21480',
    storageBucket: 'skipper-21480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWaUAJ-rgYIk6Iw3WdgYSwYPVjIvSK41s',
    appId: '1:1066116333121:ios:a792ee59fc1c0624b650c0',
    messagingSenderId: '1066116333121',
    projectId: 'skipper-21480',
    storageBucket: 'skipper-21480.appspot.com',
    iosClientId: '1066116333121-4c4dsquvm510comchodor9emgb16bmsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.locadly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWaUAJ-rgYIk6Iw3WdgYSwYPVjIvSK41s',
    appId: '1:1066116333121:ios:aa52f33dab3c2a87b650c0',
    messagingSenderId: '1066116333121',
    projectId: 'skipper-21480',
    storageBucket: 'skipper-21480.appspot.com',
    iosClientId: '1066116333121-sj0a0p3c2ff2fktqb3133433euh40m59.apps.googleusercontent.com',
    iosBundleId: 'com.example.locadly.RunnerTests',
  );
}
